[package]
name = "id_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
derivative = "2.2.0"
derive-new = "0.6.0"
ipnetwork = "0.20.0"
rangemap = "1.4.0"
thiserror = "1.0.50"
