name: Rust

on:
  push:
    branches: [ "tun2socks5" ]
  pull_request:
    branches: [ "tun2socks5" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose -r
    # - name: Run tests
    #   run: cargo test --verbose
